-- MySQL Script generated by MySQL Workbench
-- seg 01 set 2025 08:34:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SACC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SACC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SACC` ;
-- -----------------------------------------------------
-- Schema phpmyadmin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema phpmyadmin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phpmyadmin` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `SACC` ;

-- -----------------------------------------------------
-- Table `SACC`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SACC`.`Status` (
  `id_status` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `Trabalhos_id_trabalhos` INT NOT NULL,
  PRIMARY KEY (`id_status`),
  INDEX `fk_Status_Trabalhos1_idx` (`Trabalhos_id_trabalhos` ASC) VISIBLE,
  CONSTRAINT `fk_Status_Trabalhos1`
    FOREIGN KEY (`Trabalhos_id_trabalhos`)
    REFERENCES `SACC`.`Trabalhos` (`id_trabalhos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SACC`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SACC`.`Categoria` (
  `id_categoria` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SACC`.`Contatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SACC`.`Contatos` (
  `id_contatos` INT NOT NULL,
  `telefone` INT(11) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_contatos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SACC`.`Jurados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SACC`.`Jurados` (
  `id_jurados` INT NOT NULL,
  `usu_jurado` VARCHAR(45) NULL,
  `pass_jurado` INT(6) NULL,
  `cpf` INT(11) NULL,
  `contato` INT NULL,
  `categoria` INT NULL,
  PRIMARY KEY (`id_jurados`),
  INDEX `fk_id_categoria` (`categoria` ASC) VISIBLE,
  INDEX `fk_Jurados_1_idx` (`contato` ASC) VISIBLE,
  CONSTRAINT `fk_id_categoria`
    FOREIGN KEY (`categoria`)
    REFERENCES `SACC`.`Categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jurados_1`
    FOREIGN KEY (`contato`)
    REFERENCES `SACC`.`Contatos` (`id_contatos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SACC`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SACC`.`Area` (
  `id_areas` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `Trabalhos_id_trabalhos` INT NOT NULL,
  PRIMARY KEY (`id_areas`),
  INDEX `fk_Area_Trabalhos1_idx` (`Trabalhos_id_trabalhos` ASC) VISIBLE,
  CONSTRAINT `fk_Area_Trabalhos1`
    FOREIGN KEY (`Trabalhos_id_trabalhos`)
    REFERENCES `SACC`.`Trabalhos` (`id_trabalhos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SACC`.`Trabalhos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SACC`.`Trabalhos` (
  `id_trabalhos` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `observacoes` VARCHAR(45) NULL,
  `status` INT NULL,
  `jurado` INT NULL,
  `escola` INT NULL,
  `area` INT NULL,
  `categoria` INT NULL,
  `Status_id_status` INT NOT NULL,
  `Area_id_areas` INT NOT NULL,
  `Escolas_id_escolas` INT NOT NULL,
  PRIMARY KEY (`id_trabalhos`),
  INDEX `fk_id_status_idx` (`status` ASC) VISIBLE,
  INDEX `fk_id_escola_idx` (`escola` ASC) VISIBLE,
  INDEX `fk_id_jurado_idx` (`jurado` ASC) VISIBLE,
  INDEX `fk_id_area_idx` (`area` ASC) VISIBLE,
  INDEX `fk_id_categoria_idx` (`categoria` ASC) VISIBLE,
  INDEX `fk_Trabalhos_Status1_idx` (`Status_id_status` ASC) VISIBLE,
  INDEX `fk_Trabalhos_Area1_idx` (`Area_id_areas` ASC) VISIBLE,
  INDEX `fk_Trabalhos_Escolas1_idx` (`Escolas_id_escolas` ASC) VISIBLE,
  CONSTRAINT `fk_id_status`
    FOREIGN KEY (`status`)
    REFERENCES `SACC`.`Status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_escola`
    FOREIGN KEY (`escola`)
    REFERENCES `SACC`.`Escolas` (`id_escolas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_jurado`
    FOREIGN KEY (`jurado`)
    REFERENCES `SACC`.`Jurados` (`id_jurados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_area`
    FOREIGN KEY (`area`)
    REFERENCES `SACC`.`Area` (`id_areas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_categoria`
    FOREIGN KEY (`categoria`)
    REFERENCES `SACC`.`Categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabalhos_Status1`
    FOREIGN KEY (`Status_id_status`)
    REFERENCES `SACC`.`Status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabalhos_Area1`
    FOREIGN KEY (`Area_id_areas`)
    REFERENCES `SACC`.`Area` (`id_areas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabalhos_Escolas1`
    FOREIGN KEY (`Escolas_id_escolas`)
    REFERENCES `SACC`.`Escolas` (`id_escolas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SACC`.`Escolas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SACC`.`Escolas` (
  `id_escolas` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `focalizada` TINYINT(1) NULL,
  `ide` VARCHAR(45) NULL,
  `municipio` VARCHAR(45) NULL,
  `Trabalhos_id_trabalhos` INT NOT NULL,
  PRIMARY KEY (`id_escolas`),
  INDEX `fk_Escolas_Trabalhos1_idx` (`Trabalhos_id_trabalhos` ASC) VISIBLE,
  CONSTRAINT `fk_Escolas_Trabalhos1`
    FOREIGN KEY (`Trabalhos_id_trabalhos`)
    REFERENCES `SACC`.`Trabalhos` (`id_trabalhos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SACC`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SACC`.`Administrador` (
  `id_administrador` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `senha` INT(6) NULL,
  PRIMARY KEY (`id_administrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SACC`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SACC`.`Notas` (
  `id_notas` INT NOT NULL,
  `notas` FLOAT(4) NULL,
  `trabalho` INT NULL,
  `jurado` INT NULL,
  `escola` INT NULL,
  PRIMARY KEY (`id_notas`),
  INDEX `fk_id_trabalho_idx` (`trabalho` ASC) VISIBLE,
  INDEX `fk_id_escola_idx` (`escola` ASC) VISIBLE,
  INDEX `fk_id_jurado_idx` (`jurado` ASC) VISIBLE,
  CONSTRAINT `fk_id_trabalho`
    FOREIGN KEY (`trabalho`)
    REFERENCES `SACC`.`Trabalhos` (`id_trabalhos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_escola`
    FOREIGN KEY (`escola`)
    REFERENCES `SACC`.`Escolas` (`id_escolas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_jurado`
    FOREIGN KEY (`jurado`)
    REFERENCES `SACC`.`Jurados` (`id_jurados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `phpmyadmin` ;

-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__bookmark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__bookmark` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dbase` VARCHAR(255) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `user` VARCHAR(255) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `label` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL DEFAULT '',
  `query` TEXT COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Bookmarks';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__central_columns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__central_columns` (
  `db_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `col_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `col_type` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `col_length` TEXT COLLATE 'utf8mb3_bin' NULL DEFAULT NULL,
  `col_collation` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `col_isNull` TINYINT(1) NOT NULL,
  `col_extra` VARCHAR(255) COLLATE 'utf8mb3_bin' NULL DEFAULT '',
  `col_default` TEXT COLLATE 'utf8mb3_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`db_name`, `col_name`))
ENGINE = InnoDB
COMMENT = 'Central list of columns';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__column_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__column_info` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `db_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `table_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `column_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `comment` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL DEFAULT '',
  `mimetype` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL DEFAULT '',
  `transformation` VARCHAR(255) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `transformation_options` VARCHAR(255) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `input_transformation` VARCHAR(255) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `input_transformation_options` VARCHAR(255) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `db_name` (`db_name` ASC, `table_name` ASC, `column_name` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Column information for phpMyAdmin';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__designer_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__designer_settings` (
  `username` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `settings_data` TEXT COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
COMMENT = 'Settings related to Designer';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__export_templates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__export_templates` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `export_type` VARCHAR(10) COLLATE 'utf8mb3_bin' NOT NULL,
  `template_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `template_data` TEXT COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `u_user_type_template` (`username` ASC, `export_type` ASC, `template_name` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Saved export templates';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__favorite` (
  `username` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `tables` TEXT COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
COMMENT = 'Favorite tables';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__history` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `db` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `table` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `timevalue` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sqlquery` TEXT COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `username` (`username` ASC, `db` ASC, `table` ASC, `timevalue` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'SQL history for phpMyAdmin';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__navigationhiding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__navigationhiding` (
  `username` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `item_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `item_type` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `db_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `table_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`username`, `item_name`, `item_type`, `db_name`, `table_name`))
ENGINE = InnoDB
COMMENT = 'Hidden items of navigation tree';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__pdf_pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__pdf_pages` (
  `db_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `page_nr` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `page_descr` VARCHAR(50) CHARACTER SET 'utf8mb3' NOT NULL DEFAULT '',
  PRIMARY KEY (`page_nr`),
  INDEX `db_name` (`db_name` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'PDF relation pages for phpMyAdmin';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__recent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__recent` (
  `username` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `tables` TEXT COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
COMMENT = 'Recently accessed tables';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__relation` (
  `master_db` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `master_table` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `master_field` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `foreign_db` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `foreign_table` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `foreign_field` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  PRIMARY KEY (`master_db`, `master_table`, `master_field`),
  INDEX `foreign_field` (`foreign_db` ASC, `foreign_table` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Relation table';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__savedsearches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__savedsearches` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `db_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `search_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `search_data` TEXT COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `u_savedsearches_username_dbname` (`username` ASC, `db_name` ASC, `search_name` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Saved searches';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__table_coords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__table_coords` (
  `db_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `table_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `pdf_page_number` INT NOT NULL DEFAULT '0',
  `x` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  `y` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`db_name`, `table_name`, `pdf_page_number`))
ENGINE = InnoDB
COMMENT = 'Table coordinates for phpMyAdmin PDF output';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__table_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__table_info` (
  `db_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `table_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `display_field` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  PRIMARY KEY (`db_name`, `table_name`))
ENGINE = InnoDB
COMMENT = 'Table information for phpMyAdmin';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__table_uiprefs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__table_uiprefs` (
  `username` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `db_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `table_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `prefs` TEXT COLLATE 'utf8mb3_bin' NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`username`, `db_name`, `table_name`))
ENGINE = InnoDB
COMMENT = 'Tables\' UI preferences';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__tracking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__tracking` (
  `db_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `table_name` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `version` INT UNSIGNED NOT NULL,
  `date_created` DATETIME NOT NULL,
  `date_updated` DATETIME NOT NULL,
  `schema_snapshot` TEXT COLLATE 'utf8mb3_bin' NOT NULL,
  `schema_sql` TEXT COLLATE 'utf8mb3_bin' NULL DEFAULT NULL,
  `data_sql` LONGTEXT COLLATE 'utf8mb3_bin' NULL DEFAULT NULL,
  `tracking` SET('UPDATE', 'REPLACE', 'INSERT', 'DELETE', 'TRUNCATE', 'CREATE DATABASE', 'ALTER DATABASE', 'DROP DATABASE', 'CREATE TABLE', 'ALTER TABLE', 'RENAME TABLE', 'DROP TABLE', 'CREATE INDEX', 'DROP INDEX', 'CREATE VIEW', 'ALTER VIEW', 'DROP VIEW') NULL DEFAULT NULL,
  `tracking_active` INT UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`db_name`, `table_name`, `version`))
ENGINE = InnoDB
COMMENT = 'Database changes tracking for phpMyAdmin';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__userconfig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__userconfig` (
  `username` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `timevalue` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `config_data` TEXT COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
COMMENT = 'User preferences storage for phpMyAdmin';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__usergroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__usergroups` (
  `usergroup` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `tab` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `allowed` ENUM('Y', 'N') COLLATE 'utf8mb3_bin' NOT NULL DEFAULT 'N',
  PRIMARY KEY (`usergroup`, `tab`, `allowed`))
ENGINE = InnoDB
COMMENT = 'User groups with configured menu items';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__users` (
  `username` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  `usergroup` VARCHAR(64) COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`username`, `usergroup`))
ENGINE = InnoDB
COMMENT = 'Users and their assignments to user groups';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
